### ISSUE TITLE
Query - Looking for your help, comments and suggestions

### ISSUE THREAD

**Issue by envyvy** [sunilmhta/Hindi-Soft-Keyboard#1]
Hi Sunil,
I want to build an Indic Keyboard app, starting from devanaagri script. 
Saw your project on github. 
Will you be able to help me in this? 
Cheers,
Vikas

**Comment by sunilmhta** [comment]
Hi Vikas,
I can help but it depends on the time. Right now my placements are going
on, so I can't help. I will be free after December. Then after I can help.

Cheers,
Sunil

**Comment by envyvy** [comment]
Hi Sunil,
Thanks for your reply. That is surely one of the busiest and most crucial time. My best wishes to you. 
Will contact you probably Jan next year.
#ShubhamAstu
Cheers, Vikas

**Comment by sunilmhta** [comment]
Thanks Vikas. Looking forward to help you. :D

**Comment by envyvy** [comment]
Hi Sunil,
Hope you have sailed through well. 
Please let me know when you would be able help/guide me through my hobby app. 
Again no rush.
Also please email me at envyvy@gmail.com when possible as it is a bit tedious to converse on github. 
I have listed a set of 21 specs, will share with you on email to know which ones are practically possible. 
Thanks. Vikas
